version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - VITE_JSON_SERVER_1=http://json-server-1:80
      - VITE_JSON_SERVER_2=http://json-server-2:80
    depends_on:
      - json-server-1
      - json-server-2
    networks:
      - app-network
  json-server-1:
    image: clue/json-server
    ports:
      - "4001:80"
    volumes:
      - ./db-step1.json:/data/db.json
    networks:
      - app-network
  json-server-2:
    image: clue/json-server
    ports:
      - "4002:80"
    volumes:
      - ./db-step2.json:/data/db.json
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
