services:
  # Frontend service
  - type: web
    runtime: docker
    name: frontend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: VITE_JSON_SERVER_1
        value: https://json-server-1.onrender.com
      - key: VITE_JSON_SERVER_2
        value: https://json-server-2.onrender.com

  # JSON Server 1
  - type: web
    runtime: docker
    name: json-server-1
    dockerfilePath: ./Dockerfile.json-server-1

  # JSON Server 2
  - type: web
    runtime: docker
    name: json-server-2
    dockerfilePath: ./Dockerfile.json-server-2
